package com.bfg.backend.model;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

/**
 * The model for the Alliance database. Similar to a guild or group. 
 */
@Entity // This tells Hibernate to make a table out of this class
@Table(name="Alliance")
public class Alliance {

//	@Id
//	@GeneratedValue(strategy = GenerationType.AUTO)
//	@Column(name = "faction_id")
//	private Long guild_id;

	@Id
	@Column(name = "alliance_name")
	private String alliance_name;
	
	@Column(name = "admiral")
	private String admiral;
	
	@Column(name = "captains")
	private String captains;	// JSON string of captains
	
	@Column(name = "members")
	private String members;		// JSON string of members
	
	/**
	 * Empty constructor
	 */
	public Alliance() {}

	/**
	 * Returns the guild_id
	 * @return the guild_id
	 */
//	public Long getGuild_id() {
//		return guild_id;
//	}

	/**
	 * Sets the guild_id
	 * @param guild_id Autogenerated
	 */
//	public void setGuild_id(Long guild_id) {
//		this.guild_id = guild_id;
//	}

	/**
	 * Retrieves the name of the guild
	 * @return the name of the guild
	 */
	public String getAlliance_name() {
		return alliance_name;
	}

	/**
	 * Sets the name for the guild
	 * @param guild_name The name of the guild
	 */
	public void setAlliance_name(String alliance_name) {
		this.alliance_name = alliance_name;
	}
	
	public String getAdmiral() {
		return admiral;
	}
	
	public void setAdmiral(String admiral) {
		this.admiral = admiral;
	}
	
	public String getCaptains() {
		return captains;
	}
	
	public void addCaptain(String captain) {
		JsonParser parser = new JsonParser();
		JsonObject caps = parser.parse(captains).getAsJsonObject();
		caps.addProperty("captain", captain);
		captains = caps.toString();
		
		// Add captain to the JSON
	}
	
	public JsonObject getCaptainsAsJson() {
		// TODO
		return null;
	}
	
	public String getMembers() {
		return members;
	}
	
	public void addMember(String member) {
		// TODO
	}
	
	public JsonObject getMemberAsJson() {
		// TODO
		return null;
	}
}