package com.bfg.backend.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * The model for the Alliance database. Similar to a guild or group. 
 */
@Entity // This tells Hibernate to make a table out of this class
@Table(name="Alliance")
public class Alliance {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "faction_id")
	private Long guild_id;

	@Column(name = "faction_name")
	private String guild_name;
	
	/**
	 * Empty constructor
	 */
	public Alliance() {
		
	}

	/**
	 * Returns the guild_id
	 * @return the guild_id
	 */
	public Long getGuild_id() {
		return guild_id;
	}

	/**
	 * Sets the guild_id
	 * @param guild_id Autogenerated
	 */
	public void setGuild_id(Long guild_id) {
		this.guild_id = guild_id;
	}

	/**
	 * Retrieves the name of the guild
	 * @return the name of the guild
	 */
	public String getGuild_name() {
		return guild_name;
	}

	/**
	 * Sets the name for the guild
	 * @param guild_name The name of the guild
	 */
	public void setGuild_name(String guild_name) {
		this.guild_name = guild_name;
	}	
}